// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-QcksKcXsqC6FyzifAlWBOqoXdIDVopE',
    appId: '1:142695238755:web:07c73ea9f57686c5debc56',
    messagingSenderId: '142695238755',
    projectId: 'campushub-27f6a',
    authDomain: 'campushub-27f6a.firebaseapp.com',
    storageBucket: 'campushub-27f6a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyA6imHLgAiwQMLzttCqKhQTjZYKQae4g',
    appId: '1:142695238755:android:5e996d1e78310615debc56',
    messagingSenderId: '142695238755',
    projectId: 'campushub-27f6a',
    storageBucket: 'campushub-27f6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbTHxOSwpHyZk2-6oeDnJp8SjRJWRHehE',
    appId: '1:142695238755:ios:0ed132015ba451fedebc56',
    messagingSenderId: '142695238755',
    projectId: 'campushub-27f6a',
    storageBucket: 'campushub-27f6a.firebasestorage.app',
    iosBundleId: 'com.example.campusHub',
  );
}
